/* Server-backed generation (M1 spike). See srvgen.h. */
#include "srvgen.h"
#include "util.h"      /* jx_get_string */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>

static double now_s(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec / 1e9;
}

static pid_t srvgen_wait_health(pid_t pid, int port, int timeout_s);

/* JSON-escape a string (no surrounding quotes). Caller frees. */
static char *json_escape(const char *s) {
    size_t n = strlen(s), cap = n * 2 + 16, k = 0;
    char *o = malloc(cap);
    if (!o) return NULL;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char) s[i];
        if (k + 8 > cap) { cap *= 2; char *t = realloc(o, cap); if (!t) { free(o); return NULL; } o = t; }
        switch (c) {
            case '"':  o[k++] = '\\'; o[k++] = '"';  break;
            case '\\': o[k++] = '\\'; o[k++] = '\\'; break;
            case '\n': o[k++] = '\\'; o[k++] = 'n';  break;
            case '\r': o[k++] = '\\'; o[k++] = 'r';  break;
            case '\t': o[k++] = '\\'; o[k++] = 't';  break;
            default:
                if (c < 0x20) k += (size_t) snprintf(o + k, 8, "\\u%04x", c);
                else o[k++] = (char) c;
        }
    }
    o[k] = 0;
    return o;
}

pid_t srvgen_spawn(const char *server_bin, const char *model_path, int ngl, int ctx,
                   const char *extra, int port, const char *logpath, int timeout_s) {
    char nglbuf[16], ctxbuf[16], portbuf[16];
    snprintf(nglbuf,  sizeof nglbuf,  "%d", ngl);
    snprintf(ctxbuf,  sizeof ctxbuf,  "%d", ctx);
    snprintf(portbuf, sizeof portbuf, "%d", port);

    /* base argv + up to 24 tokens from `extra` (space-split) */
    char *argv[48];
    int a = 0;
    argv[a++] = (char *) server_bin;
    argv[a++] = "-m";   argv[a++] = (char *) model_path;
    argv[a++] = "-ngl"; argv[a++] = nglbuf;
    argv[a++] = "-c";   argv[a++] = ctxbuf;
    argv[a++] = "--host"; argv[a++] = "127.0.0.1";
    argv[a++] = "--port"; argv[a++] = portbuf;

    char *extra_copy = extra ? strdup(extra) : NULL;
    if (extra_copy) {
        char *save = NULL, *tok = strtok_r(extra_copy, " ", &save);
        while (tok && a < 46) { argv[a++] = tok; tok = strtok_r(NULL, " ", &save); }
    }
    argv[a] = NULL;

    pid_t pid = fork();
    if (pid < 0) { free(extra_copy); return -1; }
    if (pid == 0) {
        /* child: redirect stdout+stderr to the log, then exec the server */
        int fd = open(logpath, O_WRONLY | O_CREAT | O_TRUNC, 0644);
        if (fd >= 0) { dup2(fd, 1); dup2(fd, 2); close(fd); }
        setsid();  /* own process group so srvgen_kill can't miss it */
        execvp(server_bin, argv);
        _exit(127);
    }
    free(extra_copy);

    return srvgen_wait_health(pid, port, timeout_s);
}

/* Poll /health on 127.0.0.1:port until OK (returns pid) or the child dies /
 * timeout elapses (kills it, returns -1). Shared by both spawn paths. */
static pid_t srvgen_wait_health(pid_t pid, int port, int timeout_s) {
    char cmd[256];
    snprintf(cmd, sizeof cmd,
             "curl -sf -o /dev/null http://127.0.0.1:%d/health", port);
    for (int i = 0; i < timeout_s; i++) {
        int st; if (waitpid(pid, &st, WNOHANG) == pid) return -1;   /* child died */
        if (system(cmd) == 0) return pid;                            /* ready */
        sleep(1);
    }
    srvgen_kill(pid);
    return -1;
}

int srvgen_write_launch_script(const SrvLaunch *cfg, const char *path) {
    if (!cfg || !path) return -1;
    /* Best-effort create of the parent dir (e.g. .basi/). */
    char dir[768]; snprintf(dir, sizeof dir, "%s", path);
    char *slash = strrchr(dir, '/');
    if (slash) { *slash = 0; if (dir[0]) mkdir(dir, 0755); }   /* ignore EEXIST */

    FILE *f = fopen(path, "w");
    if (!f) return -1;
    const char *host = (cfg->host && *cfg->host) ? cfg->host : "127.0.0.1";
    const char *bin  = (cfg->server_bin && *cfg->server_bin) ? cfg->server_bin
                       : "/home/alberto/llama.cpp/build_vulkan/bin/llama-server";
    const char *model = cfg->model_path ? cfg->model_path : "";
    fprintf(f, "#!/usr/bin/env bash\n");
    fprintf(f, "# Generated by BASI-CLI — how to run llama-server for this model.\n");
    fprintf(f, "# Edit freely and run standalone; BASI execs this to launch the server.\n");
    fprintf(f, "# Keep --host/--port matching what BASI connects to (%s:%d).\n", host, cfg->port);
    fprintf(f, "# BASI-MODEL: %s\n\n", model);
    fprintf(f, "exec \"%s\" \\\n", bin);
    fprintf(f, "  -m \"%s\" \\\n", model);
    fprintf(f, "  -ngl %d -c %d \\\n", cfg->ngl, cfg->ctx);
    fprintf(f, "  --host %s --port %d", host, cfg->port);
    /* --kv-unified keeps each slot at the FULL -c; without it -c is split N ways. */
    if (cfg->n_parallel > 1) fprintf(f, " \\\n  -np %d --kv-unified", cfg->n_parallel);
    if (cfg->flash_attn) fprintf(f, " \\\n  -fa on");
    if (cfg->spec_type && *cfg->spec_type)
        fprintf(f, " \\\n  --spec-type %s --spec-draft-n-max %d", cfg->spec_type, cfg->spec_nmax);
    if (cfg->jinja) fprintf(f, " \\\n  --jinja");
    if (cfg->reasoning_format && *cfg->reasoning_format)
        fprintf(f, " \\\n  --reasoning-format %s", cfg->reasoning_format);
    fprintf(f, "\n");
    fclose(f);
    chmod(path, 0755);
    return 0;
}

int srvgen_script_has_slots(const char *path, int need) {
    if (!path || need <= 1) return 1;          /* single slot: nothing required */
    FILE *f = fopen(path, "r");
    if (!f) return 0;
    int slots = 0, unified = 0;
    char line[1024];
    while (fgets(line, sizeof line, f)) {
        if (line[0] == '#') continue;          /* the doc comments mention the flags */
        if (strstr(line, "--kv-unified")) unified = 1;
        const char *np = strstr(line, "-np ");
        if (np) slots = atoi(np + 4);
        else if ((np = strstr(line, "--parallel ")) != NULL) slots = atoi(np + 11);
    }
    fclose(f);
    return slots >= need && unified;
}

int srvgen_script_matches(const char *path, const char *model_path) {
    if (!path || !model_path) return 0;
    FILE *f = fopen(path, "r");
    if (!f) return 0;
    char line[1024]; int match = 0;
    while (fgets(line, sizeof line, f)) {
        char *m = strstr(line, "# BASI-MODEL:");
        if (!m) continue;
        m += strlen("# BASI-MODEL:");
        while (*m == ' ') m++;
        size_t len = strlen(m);
        while (len > 0 && (m[len-1]=='\n' || m[len-1]=='\r' || m[len-1]==' ')) len--;
        match = (len == strlen(model_path) && strncmp(m, model_path, len) == 0);
        break;
    }
    fclose(f);
    return match;
}

pid_t srvgen_spawn_script(const char *path, int port, const char *logpath, int timeout_s) {
    pid_t pid = fork();
    if (pid < 0) return -1;
    if (pid == 0) {
        int fd = open(logpath, O_WRONLY | O_CREAT | O_TRUNC, 0644);
        if (fd >= 0) { dup2(fd, 1); dup2(fd, 2); close(fd); }
        setsid();                       /* own group so srvgen_kill reaches it */
        execlp("bash", "bash", path, (char *) NULL);
        _exit(127);
    }
    return srvgen_wait_health(pid, port, timeout_s);
}

char *srvgen_complete(int port, const char *prompt, int n_predict,
                      const SrvSampling *samp, const char *grammar_fragment,
                      void (*emit)(const char *chunk, void *ud), void *ud,
                      double *tps, int *n_out) {
    char *esc = json_escape(prompt);
    if (!esc) return NULL;

    /* write the request body to a temp file (avoids quoting a big prompt on argv) */
    char reqpath[] = "/tmp/basi_srvreq_XXXXXX";
    int rfd = mkstemp(reqpath);
    if (rfd < 0) { free(esc); return NULL; }
    FILE *rf = fdopen(rfd, "w");
    fprintf(rf, "{\"prompt\":\"%s\",\"n_predict\":%d", esc, n_predict);
    /* Sampling knobs mirroring BASI's native chain; each omitted at its sentinel
       so the server falls back to its own default. temperature==0 => greedy, and
       we also pin top_k:1 so a sampler tail can't reintroduce randomness. */
    if (samp) {
        if (samp->temperature >= 0)   fprintf(rf, ",\"temperature\":%.3f", samp->temperature);
        if (samp->temperature == 0.0) fprintf(rf, ",\"top_k\":1");
        else if (samp->top_k > 0)     fprintf(rf, ",\"top_k\":%d", samp->top_k);
        if (samp->repeat_penalty > 1.0) {
            fprintf(rf, ",\"repeat_penalty\":%.3f", samp->repeat_penalty);
            if (samp->repeat_last_n >= 0) fprintf(rf, ",\"repeat_last_n\":%d", samp->repeat_last_n);
        }
        if (samp->min_p >= 0)                       fprintf(rf, ",\"min_p\":%.4f", samp->min_p);
        if (samp->top_p >= 0 && samp->top_p < 1.0)  fprintf(rf, ",\"top_p\":%.4f", samp->top_p);
        if (samp->seed >= 0)                        fprintf(rf, ",\"seed\":%ld", samp->seed);
    }
    /* grammar_fragment is caller-provided valid JSON, spliced verbatim, e.g.
       "grammar":"…","grammar_lazy":true,"grammar_triggers":[…]  */
    if (grammar_fragment && *grammar_fragment) fprintf(rf, ",%s", grammar_fragment);
    fprintf(rf, ",\"cache_prompt\":true,\"stream\":true}");
    fclose(rf);
    free(esc);

    char cmd[512];
    snprintf(cmd, sizeof cmd,
        "curl -N -s -X POST http://127.0.0.1:%d/completion "
        "-H 'Content-Type: application/json' --data-binary @%s", port, reqpath);

    FILE *p = popen(cmd, "r");
    if (!p) { unlink(reqpath); return NULL; }

    StringBuf out; sb_init(&out);
    char *line = NULL; size_t cap = 0; ssize_t len;
    int n_tok = 0; int done = 0;
    double t0 = now_s();
    while ((len = getline(&line, &cap, p)) != -1) {
        /* SSE frames: "data: {json}\n" */
        char *j = strstr(line, "data:");
        if (!j) continue;
        j += 5; while (*j == ' ') j++;
        char *content = jx_get_string(j, "content");
        if (content) {
            if (content[0]) { sb_append_str(&out, content); if (emit) emit(content, ud); n_tok++; }
            free(content);
        }
        if (strstr(j, "\"stop\":true")) { done = 1; break; }
    }
    free(line);
    pclose(p);
    unlink(reqpath);

    double dt = now_s() - t0;
    if (tps)   *tps = (dt > 0) ? n_tok / dt : 0.0;
    if (n_out) *n_out = n_tok;
    (void) done;
    return sb_to_str(&out);
}

void srvgen_kill(pid_t pid) {
    if (pid <= 0) return;
    kill(-pid, SIGTERM);       /* whole process group (setsid in child) */
    for (int i = 0; i < 30; i++) {
        int st; if (waitpid(pid, &st, WNOHANG) == pid) return;
        usleep(100000);
    }
    kill(-pid, SIGKILL);
    waitpid(pid, NULL, 0);
}

static void print_emit(const char *chunk, void *ud) {
    (void) ud;
    fputs(chunk, stdout); fflush(stdout);
}

void srvgen_selftest(const char *model_path, int ngl, int ctx) {
    const char *server_bin = getenv("BASI_SERVER_BIN");
    if (!server_bin || !*server_bin)
        server_bin = "/home/alberto/llama.cpp/build_vulkan/bin/llama-server";
    const int port = 8181;

    /* spec flags from env: BASI_SPEC=draft-mtp BASI_SPEC_NMAX=1 -> MTP for free */
    char extra[128] = "";
    const char *spec = getenv("BASI_SPEC");
    if (spec && *spec) {
        int nmax = 1; const char *e = getenv("BASI_SPEC_NMAX"); if (e && *e) nmax = atoi(e);
        snprintf(extra, sizeof extra, "-fa on --spec-type %s --spec-draft-n-max %d", spec, nmax);
    }

    int n_predict = 128; { const char *e = getenv("BASI_SPEC_N"); if (e && *e) n_predict = atoi(e); }
    const char *prompt = getenv("BASI_SPEC_PROMPT");
    if (!prompt || !*prompt)
        prompt = "Write a C function that reverses a string in place. Explain your approach first.";

    fprintf(stderr, "\n=== server-gen self-test: ngl=%d ctx=%d spec='%s' ===\n", ngl, ctx, extra);
    fprintf(stderr, "[srv] spawning llama-server (loads the model — the ONLY copy)...\n");
    double ts0 = now_s();
    pid_t pid = srvgen_spawn(server_bin, model_path, ngl, ctx, extra[0] ? extra : NULL,
                             port, "/tmp/basi_srvgen.log", 300);
    if (pid < 0) { fprintf(stderr, "[srv] spawn/health FAILED (see /tmp/basi_srvgen.log)\n"); return; }
    fprintf(stderr, "[srv] ready in %.1fs. streaming completion:\n---\n", now_s() - ts0);

    /* optional grammar round-trip test: BASI_SRV_GRAMMAR="root ::= \"yes\" | \"no\"" */
    char *frag = NULL;
    const char *grammar = getenv("BASI_SRV_GRAMMAR");
    if (grammar && *grammar) {
        char *ge = json_escape(grammar);
        if (ge) { size_t m = strlen(ge) + 16; frag = malloc(m); snprintf(frag, m, "\"grammar\":\"%s\"", ge); free(ge); }
        fprintf(stderr, "[srv] sending grammar (%zu bytes)\n", strlen(grammar));
    }

    double tps = 0; int n = 0;
    SrvSampling greedy = { .temperature = 0.0, .repeat_penalty = 0, .repeat_last_n = -1,
                           .min_p = -1, .top_k = 0, .top_p = -1, .seed = -1 };
    char *txt = srvgen_complete(port, prompt, n_predict, &greedy, frag, print_emit, NULL, &tps, &n);
    free(frag);
    fprintf(stderr, "\n---\n[srv] %d tokens, %.2f tok/s\n", n, tps);

    free(txt);
    srvgen_kill(pid);
    fprintf(stderr, "[srv] server killed. done.\n");
}
